- name: install nodejs
  package: name=nodejs state=present

- name: install npm
  package: name=npm state=present

- name: install fb api
  become: yes
  become_user: ubuntu
  npm: 
    name: Schmavery/facebook-chat-api
    path: /home/ubuntu/node_modules
  
- name: clone git
  become: yes
  become_user: ubuntu
  git:
    repo: 'https://github.com/bbaugnies/Misc.git'
    dest: /home/ubuntu/git/Misc

- name: botjamin script
  copy:
    src: botjamin_pwd.txt
    dest: /home/ubuntu/pwd.txt
    owner: ubuntu
    group: ubuntu

- name: launch script
  copy:
    src: botjamin.sh
    dest: /home/ubuntu/botjamin.sh
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: git pull script
  copy:
    src: git_pull.sh
    dest: /home/ubuntu/git_pull.sh
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: botjamin cronjob
  lineinfile:
    regexp: '.*botjamin.*'
    line: '*  *    * * *   ubuntu  timeout -s 9 86400/usr/bin/flock -n /var/tmp/botjamin.lck /home/ubuntu/botjamin.sh'
    path: /etc/crontab

- name: git_pull cronjob
  lineinfile:
    regexp: '.*git_pull.*'
    line: '42  *   * * *   ubuntu  /home/ubuntu/git_pull.sh'
    path: /etc/crontab
