- name: install nodejs
  package: name=nodejs state=present

- name: install npm
  package: name=npm state=present

- name: install fb api
  become: yes
  become_user: ubuntu
  npm: 
    name: Schmavery/facebook-chat-api
    path: /home/ubuntu/node_modules

- name: install n
  become: yes
  npm:
    name: n
    global: yes

- name: get latest node
  become: yes
  command: n stable
  
- name: clone git botjamin
  become: yes
  become_user: ubuntu
  git:
    repo: 'https://github.com/bbaugnies/Misc.git'
    dest: /home/ubuntu/git/Misc
  
- name: clone git sim
  become: yes
  become_user: ubuntu
  git:
    repo: 'https://github.com/bbaugnies/Warhammer-8th-Simulator.git'
    dest: /home/ubuntu/git/Warhammer-8th-Simulator

- name: copy botjamin pwd 
  copy:
    src: botjamin_pwd.txt
    dest: /home/ubuntu/pwd.txt
    owner: ubuntu
    group: ubuntu

- name: copy launch script
  copy:
    src: botjamin.sh
    dest: /home/ubuntu/botjamin.sh
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: copy git pull script
  copy:
    src: git_pull.sh
    dest: /home/ubuntu/git_pull.sh
    owner: ubuntu
    group: ubuntu
    mode: 0777

- name: copy logrotate files
  copy:
    src: botlogs
    dest: /etc/logrotate.d/botlogs
    owner: root
    group: root
    mode: 0644

- name: botjamin cronjob
  lineinfile:
    regexp: '.*botjamin.*'
    line: '*  *    * * *   ubuntu  timeout -s 9 86400 /usr/bin/flock -n /var/tmp/botjamin.lck /home/ubuntu/botjamin.sh >> /home/ubuntu/botjamin.log 2>> /home/ubuntu/botjamin_err.log'
    path: /etc/crontab

- name: git_pull cronjob
  lineinfile:
    regexp: '.*git_pull.*'
    line: '42  *   * * *   ubuntu  /home/ubuntu/git_pull.sh >> /home/ubuntu/git.log 2>&1'
    path: /etc/crontab
