- name: update package cache
  package: update_cache=yes cache_valid_time=3600
  
- name: enable cron log
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    regexp: '^cron.*'
    line: 'cron.*                          /var/log/cron.log'

- name: remove cron from syslog
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    regexp: '^\*\.\*;auth.*'
    line: '*.*;cron,auth,authpriv.none     -/var/log/syslog'
  notify:
    - restart rsyslog
    - restart cron
